/v4l2_camera:
  ros__parameters:
    auto_exposure: 0
    blue_balance: 1000
    brightness: 50
    camera_frame_id: camera
    color_effects: 0
    color_effects_cbcr: 32896
    compression_quality: 30
    contrast: 0
    exposure_dynamic_framerate: false
    exposure_metering_mode: 0
    exposure_time_absolute: 1000
    h264_i-frame_period: 60
    h264_level: 11
    h264_profile: 4
    horizontal_flip: false
    image_raw:
      format: jpeg
      jpeg_quality: 95
      png_level: 3
    image_size:
    - 640
    - 480
    image_stabilization: false
    iso_sensitivity_auto: 1
    output_encoding: rgb8
    pixel_format: YUYV
    power_line_frequency: 1
    red_balance: 1000
    repeat_sequence_header: false
    rotate: 0
    saturation: 0
    scene_mode: 0
    sharpness: 0
    time_per_frame:
    - 1000
    - 30000
    use_sim_time: false
    vertical_flip: false
    video_bitrate: 10000000
    video_bitrate_mode: 0
    video_device: /dev/video0
    white_balance_auto_&_preset: 1
